Graylog provisioner echo debug

diff --git a/graylog/values.yaml b/graylog/values.yaml
--- a/graylog/values.yaml
+++ b/graylog/values.yaml
@@ -43,8 +43,10 @@ graylog:
         echo "Get inputs"
         INPUTS=$(curl -X GET -H "Content-Type: application/json" --user "admin:${GRAYLOG_PASSWORD_SECRET}" "http://graylog:9000/api/system/inputs")
         if [ $(echo $INPUTS | grep -c "UDP") != "1" ]; then
-            echo "Creating inputs" 
+            echo "Creating inputs"
+            echo $INPUTS 
             curl -s -X POST -H "Content-Type: application/json" -d "${SYSLOG_UDP}" --user "admin:${GRAYLOG_PASSWORD_SECRET}" "http://graylog:9000/api/system/inputs"
+            echo "Last error code $?"
         else
           echo "Not creating"
           echo $INPUTS
